config/routes.rb
CareerCriteria::Application.routes.draw do
  get "external/landing"

  get "sessions/new"

  get "pages/login"

  get "pages/home"

  get "pages/matching"

  get "pages/listing"

  get "pages/contact"

  get "resource/user_connection"

  get "resource/user_favorite_company"

  get "resource/user_favorite_match"

  get "resource/review"

  get "resource/image"

  get "resource/regerence"

  get "resource/education"

  get "user_connection/user_favorite_company"

  get "user_connection/user_favorite_match"

  get "user_connection/review"

  get "user_connection/image"

  get "user_connection/regerence"

  get "user_connection/education"

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"

  get "contact" => "external#contacts", :as => "contact"

  resources :jobs

  resources :resumes

  resources :users

  resources :companies

  root :to => "external#landing"

  resources :sessions
  

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :average_rating, :bbb_link, :city, :country, :description, :name, :password_to_join, :state, :street_address, :url, :zip
  has_many :users
  has_one :image, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_many :jobs
end

app/models/education.rb
class Education < ActiveRecord::Base
  attr_accessible :college, :degree_title, :degree_type, :description, :gpa, :minor, :minor_description, :owner_resume_id, :pending, :state, :year
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :name, :owner_id, :path
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :company_id, :current, :date_filled, :department, :description, :dress_code, :education_field_of_study, :education_requirement, :end_date, :environment, :hours, :job_type, :open, :past, :positng_user, :reference_count, :remote_available, :start_date, :title, :travel, :years_experience, :zip
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  attr_accessible :city, :country, :email, :first_name, :last_name, :owner_resume_id, :phone_number, :ref_user_id, :state, :street_address, :title, :title, :zip
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  attr_accessible :languages_spoken, :link, :note, :owner_user
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :inappropriate, :owner_id, :rating, :review, :unapproved
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :city, :company_id, :country, :email, :first_name, :job_title, :last_name, :login_id, :password, :state, :street_address, :title, :will_relocate, :will_travel, :zip, :password, :password_confirmation
  belongs_to :company
  has_many :jobs
  has_one :image
  has_many :user_favorite_compaies, :dependent => :destroy
  has_many :user_connections, :dependent => :destroy
  has_many :user_favorite_matches, :dependent => :destroy

  attr_accessor :password
  attr_reader :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/models/user_connection.rb
class UserConnection < ActiveRecord::Base
  attr_accessible :connection_id, :owner_id, :relationship, :string
end

app/models/user_favorite_match.rb
class UserFavoriteMatch < ActiveRecord::Base
  attr_accessible :job_id, :owner_id, :priority
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, :notice => 'Job was successfully created.' }
        format.json { render :json => @job, :status => :created, :location => @job }
      else
        format.html { render :action => "new" }
        format.json { render :json => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, :notice => 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
  end

  def home
  end

  def matching
  end

  def listing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/external_helper.rb
module ExternalHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resource_helper.rb
module ResourceHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :positng_user %><br />
    <%= f.number_field :positng_user %>
  </div>
  <div class="field">
    <%= f.label :job_type %><br />
    <%= f.text_field :job_type %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :education_requirement %><br />
    <%= f.text_field :education_requirement %>
  </div>
  <div class="field">
    <%= f.label :education_field_of_study %><br />
    <%= f.text_field :education_field_of_study %>
  </div>
  <div class="field">
    <%= f.label :years_experience %><br />
    <%= f.number_field :years_experience %>
  </div>
  <div class="field">
    <%= f.label :reference_count %><br />
    <%= f.number_field :reference_count %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :remote_available %><br />
    <%= f.check_box :remote_available %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :environment %><br />
    <%= f.text_area :environment %>
  </div>
  <div class="field">
    <%= f.label :dress_code %><br />
    <%= f.text_area :dress_code %>
  </div>
  <div class="field">
    <%= f.label :travel %><br />
    <%= f.number_field :travel %>
  </div>
  <div class="field">
    <%= f.label :current %><br />
    <%= f.check_box :current %>
  </div>
  <div class="field">
    <%= f.label :past %><br />
    <%= f.check_box :past %>
  </div>
  <div class="field">
    <%= f.label :open %><br />
    <%= f.check_box :open %>
  </div>
  <div class="field">
    <%= f.label :date_filled %><br />
    <%= f.date_select :date_filled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Company</th>
    <th>Positng user</th>
    <th>Job type</th>
    <th>Hours</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Description</th>
    <th>Education requirement</th>
    <th>Education field of study</th>
    <th>Years experience</th>
    <th>Reference count</th>
    <th>Zip</th>
    <th>Remote available</th>
    <th>Title</th>
    <th>Department</th>
    <th>Environment</th>
    <th>Dress code</th>
    <th>Travel</th>
    <th>Current</th>
    <th>Past</th>
    <th>Open</th>
    <th>Date filled</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.company_id %></td>
    <td><%= job.positng_user %></td>
    <td><%= job.job_type %></td>
    <td><%= job.hours %></td>
    <td><%= job.start_date %></td>
    <td><%= job.end_date %></td>
    <td><%= job.description %></td>
    <td><%= job.education_requirement %></td>
    <td><%= job.education_field_of_study %></td>
    <td><%= job.years_experience %></td>
    <td><%= job.reference_count %></td>
    <td><%= job.zip %></td>
    <td><%= job.remote_available %></td>
    <td><%= job.title %></td>
    <td><%= job.department %></td>
    <td><%= job.environment %></td>
    <td><%= job.dress_code %></td>
    <td><%= job.travel %></td>
    <td><%= job.current %></td>
    <td><%= job.past %></td>
    <td><%= job.open %></td>
    <td><%= job.date_filled %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @job.company_id %>
</p>

<p>
  <b>Positng user:</b>
  <%= @job.positng_user %>
</p>

<p>
  <b>Job type:</b>
  <%= @job.job_type %>
</p>

<p>
  <b>Hours:</b>
  <%= @job.hours %>
</p>

<p>
  <b>Start date:</b>
  <%= @job.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @job.end_date %>
</p>

<p>
  <b>Description:</b>
  <%= @job.description %>
</p>

<p>
  <b>Education requirement:</b>
  <%= @job.education_requirement %>
</p>

<p>
  <b>Education field of study:</b>
  <%= @job.education_field_of_study %>
</p>

<p>
  <b>Years experience:</b>
  <%= @job.years_experience %>
</p>

<p>
  <b>Reference count:</b>
  <%= @job.reference_count %>
</p>

<p>
  <b>Zip:</b>
  <%= @job.zip %>
</p>

<p>
  <b>Remote available:</b>
  <%= @job.remote_available %>
</p>

<p>
  <b>Title:</b>
  <%= @job.title %>
</p>

<p>
  <b>Department:</b>
  <%= @job.department %>
</p>

<p>
  <b>Environment:</b>
  <%= @job.environment %>
</p>

<p>
  <b>Dress code:</b>
  <%= @job.dress_code %>
</p>

<p>
  <b>Travel:</b>
  <%= @job.travel %>
</p>

<p>
  <b>Current:</b>
  <%= @job.current %>
</p>

<p>
  <b>Past:</b>
  <%= @job.past %>
</p>

<p>
  <b>Open:</b>
  <%= @job.open %>
</p>

<p>
  <b>Date filled:</b>
  <%= @job.date_filled %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
    <br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :login_id %><br />
    <%= f.text_field :login_id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br />
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :job_title %><br />
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :will_relocate %><br />
    <%= f.check_box :will_relocate %>
  </div>
  <div class="field">
    <%= f.label :will_travel %><br />
    <%= f.number_field :will_travel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Password</th>
    <th>Login</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Title</th>
    <th>Email</th>
    <th>Street address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Country</th>
    <th>Job title</th>
    <th>Company</th>
    <th>Will relocate</th>
    <th>Will travel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.password %></td>
    <td><%= user.login_id %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.title %></td>
    <td><%= user.email %></td>
    <td><%= user.street_address %></td>
    <td><%= user.city %></td>
    <td><%= user.state %></td>
    <td><%= user.zip %></td>
    <td><%= user.country %></td>
    <td><%= user.job_title %></td>
    <td><%= user.company_id %></td>
    <td><%= user.will_relocate %></td>
    <td><%= user.will_travel %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Login:</b>
  <%= @user.login_id %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Title:</b>
  <%= @user.title %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Street address:</b>
  <%= @user.street_address %>
</p>

<p>
  <b>City:</b>
  <%= @user.city %>
</p>

<p>
  <b>State:</b>
  <%= @user.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @user.zip %>
</p>

<p>
  <b>Country:</b>
  <%= @user.country %>
</p>

<p>
  <b>Job title:</b>
  <%= @user.job_title %>
</p>

<p>
  <b>Company:</b>
  <%= @user.company_id %>
</p>

<p>
  <b>Will relocate:</b>
  <%= @user.will_relocate %>
</p>

<p>
  <b>Will travel:</b>
  <%= @user.will_travel %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>