config/routes.rb
CareerCriteria::Application.routes.draw do
  get "external/landing"

  get "sessions/new"

  get "pages/login"

  get "pages/home"

  get "pages/matching"

  get "pages/listing"

  get "pages/contact"

  get "resource/user_connection"

  get "resource/user_favorite_company"

  get "resource/user_favorite_match"

  get "resource/review"

  get "resource/image"

  get "resource/regerence"

  get "resource/education"

  get "user_connection/user_favorite_company"

  get "user_connection/user_favorite_match"

  get "user_connection/review"

  get "user_connection/image"

  get "user_connection/regerence"

  get "user_connection/education"

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"

  get "contact" => "external#contacts", :as => "contact"

  resources :jobs

  resources :resumes

  resources :users

  resources :companies

  root :to => "external#landing"

  resources :sessions
  

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :average_rating, :bbb_link, :city, :country, :description, :name, :password_to_join, :state, :street_address, :url, :zip
  has_many :users
  has_one :image, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_many :jobs
end

app/models/education.rb
class Education < ActiveRecord::Base
  attr_accessible :college, :degree_title, :degree_type, :description, :gpa, :minor, :minor_description, :owner_resume_id, :pending, :state, :year
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :name, :owner_id, :path
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :company_id, :current, :date_filled, :department, :description, :dress_code, :education_field_of_study, :education_requirement, :end_date, :environment, :hours, :job_type, :open, :past, :positng_user, :reference_count, :remote_available, :start_date, :title, :travel, :years_experience, :zip
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  attr_accessible :city, :country, :email, :first_name, :last_name, :owner_resume_id, :phone_number, :ref_user_id, :state, :street_address, :title, :title, :zip
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  attr_accessible :languages_spoken, :link, :note, :owner_user
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :inappropriate, :owner_id, :rating, :review, :unapproved
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :city, :company_id, :country, :email, :first_name, :job_title, :last_name, :login_id, :password, :state, :street_address, :title, :will_relocate, :will_travel, :zip, :password, :password_confirmation
  belongs_to :company
  has_many :jobs
  has_one :image
  has_many :user_favorite_compaies, :dependent => :destroy
  has_many :user_connections, :dependent => :destroy
  has_many :user_favorite_matches, :dependent => :destroy

  attr_accessor :password
  attr_reader :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/models/user_connection.rb
class UserConnection < ActiveRecord::Base
  attr_accessible :connection_id, :owner_id, :relationship, :string
end

app/models/user_favorite_match.rb
class UserFavoriteMatch < ActiveRecord::Base
  attr_accessible :job_id, :owner_id, :priority
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, :notice => 'Job was successfully created.' }
        format.json { render :json => @job, :status => :created, :location => @job }
      else
        format.html { render :action => "new" }
        format.json { render :json => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, :notice => 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
  end

  def home
  end

  def matching
  end

  def listing
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @resumes }
    end
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    @resume = Resume.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @resume }
    end
  end

  # GET /resumes/new
  # GET /resumes/new.json
  def new
    @resume = Resume.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @resume }
    end
  end

  # GET /resumes/1/edit
  def edit
    @resume = Resume.find(params[:id])
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(params[:resume])

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, :notice => 'Resume was successfully created.' }
        format.json { render :json => @resume, :status => :created, :location => @resume }
      else
        format.html { render :action => "new" }
        format.json { render :json => @resume.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update
    @resume = Resume.find(params[:id])

    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to @resume, :notice => 'Resume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @resume.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy

    respond_to do |format|
      format.html { redirect_to resumes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/external_helper.rb
module ExternalHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resource_helper.rb
module ResourceHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :owner_user %><br />
    <%= f.number_field :owner_user %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :languages_spoken %><br />
    <%= f.text_field :languages_spoken %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<h1>Listing resumes</h1>

<table>
  <tr>
    <th>Owner user</th>
    <th>Note</th>
    <th>Link</th>
    <th>Languages spoken</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resumes.each do |resume| %>
  <tr>
    <td><%= resume.owner_user %></td>
    <td><%= resume.note %></td>
    <td><%= resume.link %></td>
    <td><%= resume.languages_spoken %></td>
    <td><%= link_to 'Show', resume %></td>
    <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
    <td><%= link_to 'Destroy', resume, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resume', new_resume_path %>

app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Owner user:</b>
  <%= @resume.owner_user %>
</p>

<p>
  <b>Note:</b>
  <%= @resume.note %>
</p>

<p>
  <b>Link:</b>
  <%= @resume.link %>
</p>

<p>
  <b>Languages spoken:</b>
  <%= @resume.languages_spoken %>
</p>


<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>