config/routes.rb
CareerCriteria::Application.routes.draw do
  get "external/landing"

  get "sessions/new"

  get "pages/login"

  get "pages/home"

  get "pages/matching"

  get "pages/listing"

  get "pages/contact"

  get "resource/user_connection"

  get "resource/user_favorite_company"

  get "resource/user_favorite_match"

  get "resource/review"

  get "resource/image"

  get "resource/regerence"

  get "resource/education"

  get "user_connection/user_favorite_company"

  get "user_connection/user_favorite_match"

  get "user_connection/review"

  get "user_connection/image"

  get "user_connection/regerence"

  get "user_connection/education"

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"

  get "contact" => "external#contacts", :as => "contact"

  resources :jobs

  resources :resumes

  resources :users

  resources :companies

  root :to => "external#landing"

  resources :sessions
  

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :average_rating, :bbb_link, :city, :country, :description, :name, :password_to_join, :state, :street_address, :url, :zip
  has_many :users
  has_one :image, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_many :jobs
end

app/models/education.rb
class Education < ActiveRecord::Base
  attr_accessible :college, :degree_title, :degree_type, :description, :gpa, :minor, :minor_description, :owner_resume_id, :pending, :state, :year
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :name, :owner_id, :path
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :company_id, :current, :date_filled, :department, :description, :dress_code, :education_field_of_study, :education_requirement, :end_date, :environment, :hours, :job_type, :open, :past, :positng_user, :reference_count, :remote_available, :start_date, :title, :travel, :years_experience, :zip
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  attr_accessible :city, :country, :email, :first_name, :last_name, :owner_resume_id, :phone_number, :ref_user_id, :state, :street_address, :title, :title, :zip
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  attr_accessible :languages_spoken, :link, :note, :owner_user
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :inappropriate, :owner_id, :rating, :review, :unapproved
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :city, :company_id, :country, :email, :first_name, :job_title, :last_name, :login_id, :password, :state, :street_address, :title, :will_relocate, :will_travel, :zip, :password, :password_confirmation
  belongs_to :company
  has_many :jobs
  has_one :image
  has_many :user_favorite_compaies, :dependent => :destroy
  has_many :user_connections, :dependent => :destroy
  has_many :user_favorite_matches, :dependent => :destroy

  attr_accessor :password
  attr_reader :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/models/user_connection.rb
class UserConnection < ActiveRecord::Base
  attr_accessible :connection_id, :owner_id, :relationship, :string
end

app/models/user_favorite_match.rb
class UserFavoriteMatch < ActiveRecord::Base
  attr_accessible :job_id, :owner_id, :priority
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/external_helper.rb
module ExternalHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resource_helper.rb
module ResourceHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CareerCriteria</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
</head>
<body>
  <div id="container">
      <div id="header_holder">
	<div id="header" class="bg rounded-bottom">
	  <div id="header_content">
	    <div id="logo_holder">
	      <a href="/pages/home"><h1>CareerCriteria</h1></a>
	    </div>
	    <div id="user_nav">
	      <% if current_user %>
	      Logged in as <a href="/users/<%= current_user.id %>/edit">
		<%= current_user.first_name %>&nbsp;<%= current_user.last_name %></a>
	      <br />
	      <%= link_to "Log out", log_out_path %>
	      <% else %>
	      <%= link_to "Sign up", sign_up_path %> or
	      <%= link_to "log in", log_in_path %>
	      <% end %>
	    </div>
	    
	    <% flash.each do |name, msg| %>
	    <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    <% end %>
	  </div>
	</div>
      </div>
      <div id="body_holder">
	<div id="body" class="bg rounded-bottom rounded-top">
	  <%= yield %>
	  </div>
      </div>
      <div id="footer_holder">
	<div id="footer" class="bg rounded-top">
	  <div id="footer_left">&copy;&nbsp;2013&nbsp;CareerCriteria</div>
	  <div id="footer_right"><a href="/contact">Contact CareerCriteria&nbsp;&raquo;</a></div>
	</div>
      </div>
  </div>
</body>
</html>

app/views/pages/contact.html.erb
<h1>Internal Contacts Page</h1>
<p>Put more exclusive information into this page.</p>
<p>This page is only viewable to authenticated users, so we can put information like a csr phone number in here</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p>The Home Page!!!</p>

app/views/pages/listing.html.erb
<h1>Pages#listing</h1>
<p>Find me in app/views/pages/listing.html.erb</p>

app/views/pages/login.html.erb
<h1>Use Session#new for this instead</h1>

app/views/pages/matching.html.erb
<h1>Pages#matching</h1>
<p>Find me in app/views/pages/matching.html.erb</p>

app/views/resource/education.html.erb
<h1>Resource#education</h1>
<p>Find me in app/views/resource/education.html.erb</p>

app/views/resource/image.html.erb
<h1>Resource#image</h1>
<p>Find me in app/views/resource/image.html.erb</p>

app/views/resource/regerence.html.erb
<h1>Resource#regerence</h1>
<p>Find me in app/views/resource/regerence.html.erb</p>

app/views/resource/review.html.erb
<h1>Resource#review</h1>
<p>Find me in app/views/resource/review.html.erb</p>

app/views/resource/user_connection.html.erb
<h1>Resource#user_connection</h1>
<p>Find me in app/views/resource/user_connection.html.erb</p>

app/views/resource/user_favorite_company.html.erb
<h1>Resource#user_favorite_company</h1>
<p>Find me in app/views/resource/user_favorite_company.html.erb</p>

app/views/resource/user_favorite_match.html.erb
<h1>Resource#user_favorite_match</h1>
<p>Find me in app/views/resource/user_favorite_match.html.erb</p>